In [1]:
import pandas as pd

In [2]:
train_people = pd.read_csv('train_people.csv', encoding='EUC-KR')

In [3]:
train_people.head()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202309,1호선,동대문,606,32,10733,1973,9065,6382,14371,...,8967,592,2495,1,224,0,0,0,0,20231003
1,202309,1호선,동묘앞,153,1,2841,1084,3817,4586,7469,...,4019,94,1706,0,285,0,0,0,0,20231003
2,202309,1호선,서울역,596,34,8298,9361,12634,51377,39681,...,13731,2144,2462,1,186,0,0,0,0,20231003
3,202309,1호선,시청,55,3,2238,4729,3924,22886,7976,...,4323,280,842,1,25,0,0,0,0,20231003
4,202309,1호선,신설동,366,12,8783,2336,9456,8139,21484,...,9270,319,2118,0,11,0,0,0,0,20231003

In [4]:
train_people_september = train_people[train_people['사용월'] >= 202309]

In [5]:
train_people_september

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202309,1호선,동대문,606,32,10733,1973,9065,6382,14371,...,8967,592,2495,1,224,0,0,0,0,20231003
1,202309,1호선,동묘앞,153,1,2841,1084,3817,4586,7469,...,4019,94,1706,0,285,0,0,0,0,20231003
2,202309,1호선,서울역,596,34,8298,9361,12634,51377,39681,...,13731,2144,2462,1,186,0,0,0,0,20231003
3,202309,1호선,시청,55,3,2238,4729,3924,22886,7976,...,4323,280,842,1,25,0,0,0,0,20231003
4,202309,1호선,신설동,366,12,8783,2336,9456,8139,21484,...,9270,319,2118,0,11,0,0,0,0,20231003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,202309,중앙선,원덕,96,3,314,4,646,154,940,...,300,1,97,0,0,0,0,0,0,20231003
612,202309,중앙선,중랑,263,11,6776,572,9741,2009,22550,...,4842,33,451,0,0,0,0,0,0,20231003
613,202309,중앙선,지평,0,0,0,0,2,0,361,...,0,0,0,0,0,0,0,0,0,20231003
614,202309,중앙선,팔당,1,0,271,170,635,1006,1578,...,179,0,0,0,0,0,0,0,0,20231003
615,202309,중앙선,회기,1132,8,12012,4209,21552,13260,57236,...,28538,652,5007,0,1,0,0,0,0,20231003

In [6]:
train_people_september_2 = train_people_september[train_people_september['호선명'] == '2호선']
train_people_september_2

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
10,202309,2호선,강남,127,8,8402,9796,16888,51112,36360,...,22382,12122,6121,11,243,0,0,0,0,20231003
11,202309,2호선,강변(동서울터미널),24,1,8434,2370,26991,25205,72340,...,21184,900,5359,2,149,0,0,0,0,20231003
12,202309,2호선,건대입구,319,10,15855,1792,21315,14691,52752,...,33041,6899,10781,8,738,0,0,0,0,20231003
13,202309,2호선,교대(법원.검찰청),17,3,2380,6404,11312,24782,23984,...,11529,3057,3235,2,56,0,0,0,0,20231003
14,202309,2호선,구로디지털단지,461,33,36681,5064,51591,19242,134606,...,48274,3176,12598,8,701,0,0,0,0,20231003
15,202309,2호선,구의(광진구청),81,5,13571,1515,25831,20378,66523,...,22899,1109,6641,3,282,0,0,0,0,20231003
16,202309,2호선,낙성대(강감찬),11,0,11256,2149,26331,9881,79910,...,31569,1561,8546,2,356,0,0,0,0,20231003
17,202309,2호선,당산,23,3,6488,3095,15615,12285,43112,...,19009,1322,4798,5,331,0,0,0,0,20231003
18,202309,2호선,대림(구로구청),729,37,31186,3308,27883,10080,64294,...,21296,662,5462,2,327,0,0,0,0,20231003
19,202309,2호선,도림천,2,0,388,352,1069,817,3115,...,868,33,241,1,8,0,0,0,0,20231003
20,202309,2호선,동대문역사문화공원(DDP),216,7,4582,1306,4234,8439,7080,...,10379,2294,3151,8,199,0,0,0,0,20231003
21,202309,2호선,뚝섬,12,1,3204,2375,7794,15591,17690,...,7022,1633,2529,3,112,0,0,0,0,20231003
22,202309,2호선,문래,11,0,4274,2149,13975,10431,42668,...,10717,1675,3220,9,256,0,0,0,0,20231003
23,202309,2호선,방배,4,1,2613,2554,9167,11400,22424,...,8820,1463,2556,5,66,0,0,0,0,20231003
24,202309,2호선,봉천,56,4,15148,1689,28655,6663,79604,...,22845,799,7592,2,455,0,0,0,0,20231003
25,202309,2호선,사당,81,4,11928,3994,27173,32956,71508,...,37700,5673,10472,15,778,0,0,0,0,20231003
26,202309,2호선,삼성(무역센터),153,2,4308,5114,6826,41742,13917,...,6032,2303,3876,0,803,0,0,0,0,20231003
27,202309,2호선,상왕십리,59,0,5546,736,13467,5802,39331,...,12610,477,4066,3,77,0,0,0,0,20231003
28,202309,2호선,서울대입구(관악구청),4533,19,26677,2624,42765,13991,121903,...,46985,3793,17611,2,2392,0,0,0,0,20231003
29,202309,2호선,서초,2,0,1794,4397,8728,21308,17244,...,5616,871,1384,5,43,0,0,0,0,20231003
30,202309,2호선,선릉,174,3,4400,5990,11094,41977,20865,...,10276,3692,4384,3,190,0,0,0,0,20231003
31,202309,2호선,성수,69,1,5327,3583,9368,30453,22225,...,10746,3022,5596,7,787,0,1,0,0,20231003
32,202309,2호선,시청,58,0,812,1839,2358,17947,5288,...,4832,1258,1673,2,126,0,0,0,0,20231003
33,202309,2호선,신답,11,0,1217,177,1684,577,5870,...,1807,39,506,0,0,0,0,0,0,20231003
34,202309,2호선,신당,28,2,5896,1136,11727,8567,27768,...,11040,1277,3520,1,104,0,0,0,0,20231003
35,202309,2호선,신대방,303,5,23903,2234,34121,9539,87892,...,31045,956,8236,1,512,0,0,0,0,20231003
36,202309,2호선,신도림,3833,24,33671,4922,51151,20171,133620,...,49262,2362,20976,16,2193,0,0,0,0,20231003
37,202309,2호선,신림,242,10,35303,3988,66965,16229,178044,...,67935,3664,19918,18,893,0,0,0,0,20231003
38,202309,2호선,신설동,31,0,1156,265,1556,1688,4529,...,2161,84,628,0,146,0,0,0,0,20231003
39,202309,2호선,신정네거리,57,1,8705,1089,17952,2733,47599,...,10570,244,2791,1,181,0,0,0,0,20231003
40,202309,2호선,신촌,70,6,8278,2993,14362,15852,36937,...,23752,7169,6648,2,242,0,0,0,0,20231003
41,202309,2호선,아현,27,0,5015,842,10814,5928,29429,...,8843,367,2457,0,80,0,0,0,0,20231003
42,202309,2호선,양천구청,32,3,4675,950,11690,2495,32268,...,7968,143,2425,0,38,0,0,0,0,20231003
43,202309,2호선,역삼,41,3,3450,5807,8981,39536,15247,...,9317,3011,2832,3,91,0,0,0,0,20231003
44,202309,2호선,영등포구청,24,2,5349,3311,12520,13442,37706,...,12161,1341,4203,2,316,0,0,0,0,20231003
45,202309,2호선,왕십리(성동구청),892,2,6273,999,9698,7238,24366,...,11743,2824,4911,6,164,0,0,0,0,20231003
46,202309,2호선,용답,13,0,2348,382,3103,1052,8602,...,3503,97,962,0,0,0,0,0,0,20231003
47,202309,2호선,용두(동대문구청),48,1,1159,111,2046,1015,5309,...,1455,51,508,0,6,0,0,0,0,20231003
48,202309,2호선,을지로3가,20,2,1231,1682,2529,17879,6117,...,7447,3551,2043,5,80,0,0,0,0,20231003
49,202309,2호선,을지로4가,17,2,993,1288,2162,12918,5621,...,5306,972,1664,4,63,0,0,0,0,20231003
50,202309,2호선,을지로입구,33,0,2745,2687,4435,27046,10437,...,12406,3206,4649,7,577,0,0,0,0,20231003
51,202309,2호선,이대,31,1,3793,827,9070,6220,27942,...,16483,869,4418,1,136,0,0,0,0,20231003
52,202309,2호선,잠실(송파구청),95,3,12579,4877,45622,33670,109444,...,43740,4063,10244,5,508,0,0,0,0,20231003
53,202309,2호선,잠실나루,22,0,3343,2677,12516,13826,37941,...,9073,352,2932,3,75,0,0,0,0,20231003
54,202309,2호선,잠실새내,53,1,5514,867,17732,8559,57611,...,15876,2323,4917,1,240,0,0,0,0,20231003
55,202309,2호선,종합운동장,5,2,1464,759,6412,9750,16629,...,5413,368,1805,2,109,0,0,0,0,20231003
56,202309,2호선,충정로(경기대입구),52,2,3077,990,6276,6536,15921,...,5729,554,1790,2,91,0,0,0,0,20231003
57,202309,2호선,한양대,6,0,1082,525,2705,6052,5421,...,3911,1082,1402,2,45,0,0,0,0,20231003
58,202309,2호선,합정,85,9,10351,3086,18195,13053,41088,...,21756,5696,7676,3,424,0,0,0,0,20231003
59,202309,2호선,홍대입구,1069,25,29024,3391,32350,15564,60058,...,48413,12357,18470,11,1450,0,0,0,0,20231003

              사용월  04시-05시 승차인원  04시-05시 하차인원  05시-06시 승차인원  05시-06시 하차인원  \
사용월           NaN           NaN           NaN           NaN           NaN
04시-05시 승차인원  NaN      1.000000      0.561361      0.572302      0.150412
04시-05시 하차인원  NaN      0.561361      1.000000      0.853598      0.336932
05시-06시 승차인원  NaN      0.572302      0.853598      1.000000      0.312431
05시-06시 하차인원  NaN      0.150412      0.336932      0.312431      1.000000
06시-07시 승차인원  NaN      0.492098      0.630096      0.909242      0.375980
06시-07시 하차인원  NaN      0.030955      0.094558      0.087195      0.867678
07시-08시 승차인원  NaN      0.497572      0.574054      0.878735      0.309376
07시-08시 하차인원  NaN     -0.012563      0.086909     -0.004295      0.792068
08시-09시 승차인원  NaN      0.422188      0.525369      0.850110      0.307357
08시-09시 하차인원  NaN     -0.013376      0.079781     -0.034846      0.719705
09시-10시 승차인원  NaN      0.426559      0.526537      0.829587      0.391281
09시-10시 하차인원  NaN      0.018711      0.144666      0.041386      0.832925
10시-11시 승차인원  NaN      0.423034      0.547925      0.791820      0.545387
10시-11시 하차인원  NaN      0.153623      0.259928      0.198883      0.829798
11시-12시 승차인원  NaN      0.395048      0.519262      0.694967      0.701325
11시-12시 하차인원  NaN      0.214318      0.367969      0.351169      0.770160
12시-13시 승차인원  NaN      0.384919      0.509340      0.651389      0.738988
12시-13시 하차인원  NaN      0.238333      0.398121      0.391988      0.695438
13시-14시 승차인원  NaN      0.356947      0.466039      0.563430      0.785778
13시-14시 하차인원  NaN      0.240892      0.416590      0.408258      0.696754
14시-15시 승차인원  NaN      0.288670      0.399160      0.453453      0.817272
14시-15시 하차인원  NaN      0.269144      0.452085      0.484782      0.688635
15시-16시 승차인원  NaN      0.252688      0.357664      0.374739      0.819082
15시-16시 하차인원  NaN      0.311732      0.501412      0.585746      0.640025
16시-17시 승차인원  NaN      0.211279      0.326302      0.323098      0.806014
16시-17시 하차인원  NaN      0.334086      0.532348      0.636348      0.616600
17시-18시 승차인원  NaN      0.110092      0.225056      0.162480      0.813107
17시-18시 하차인원  NaN      0.347572      0.534685      0.660767      0.598379
18시-19시 승차인원  NaN      0.060740      0.182495      0.106060      0.786385
18시-19시 하차인원  NaN      0.407941      0.551812      0.734382      0.549276
19시-20시 승차인원  NaN      0.110203      0.264850      0.213374      0.807179
19시-20시 하차인원  NaN      0.448491      0.598113      0.820603      0.479870
20시-21시 승차인원  NaN      0.133519      0.271932      0.240754      0.725330
20시-21시 하차인원  NaN      0.437037      0.610918      0.842786      0.442799
21시-22시 승차인원  NaN      0.153920      0.307793      0.258105      0.712964
21시-22시 하차인원  NaN      0.443786      0.632433      0.873186      0.424198
22시-23시 승차인원  NaN      0.157961      0.340650      0.288289      0.656054
22시-23시 하차인원  NaN      0.464577      0.621981      0.871745      0.404618
23시-24시 승차인원  NaN      0.199576      0.394130      0.352223      0.563953
23시-24시 하차인원  NaN      0.505057      0.634721      0.888940      0.393195
00시-01시 승차인원  NaN      0.174833      0.373330      0.338598      0.596972
00시-01시 하차인원  NaN      0.659035      0.658535      0.880021      0.379410
01시-02시 승차인원  NaN      0.284914      0.388894      0.521718      0.467303
01시-02시 하차인원  NaN      0.862748      0.603013      0.720809      0.303401
02시-03시 승차인원  NaN           NaN           NaN           NaN           NaN
02시-03시 하차인원  NaN     -0.037677     -0.068644     -0.052796      0.076453
03시-04시 승차인원  NaN           NaN           NaN           NaN           NaN
03시-04시 하차인원  NaN           NaN           NaN           NaN           NaN
작업일자          NaN           NaN           NaN           NaN           NaN

              06시-07시 승차인원  06시-07시 하차인원  07시-08시 승차인원  07시-08시 하차인원  \
사용월                    NaN           NaN           NaN           NaN
04시-05시 승차인원      0.492098      0.030955      0.497572     -0.012563
04시-05시 하차인원      0.630096      0.094558      0.574054      0.086909
05시-06시 승차인원      0.909242      0.087195      0.878735     -0.004295
05시-06시 하차인원      0.375980      0.867678      0.309376      0.792068
06시-07시 승차인원      1.000000      0.191075      0.989148      0.025255
06시-07시 하차인원      0.191075      1.000000      0.129307      0.904273
07시-08시 승차인원      0.989148      0.129307      1.000000     -0.033729
07시-08시 하차인원      0.025255      0.904273     -0.033729      1.000000
08시-09시 승차인원      0.974622      0.162429      0.984037     -0.016729
08시-09시 하차인원     -0.032568      0.838533     -0.089247      0.970399
09시-10시 승차인원      0.965752      0.279173      0.963675      0.088561
09시-10시 하차인원      0.061735      0.886455     -0.014553      0.949597
10시-11시 승차인원      0.920790      0.459595      0.896401      0.281034
10시-11시 하차인원      0.235751      0.866744      0.149672      0.861156
11시-12시 승차인원      0.811385      0.636155      0.765566      0.494031
11시-12시 하차인원      0.395520      0.787355      0.300959      0.722962
12시-13시 승차인원      0.751351      0.681640      0.698151      0.555310
12시-13시 하차인원      0.426558      0.708412      0.331511      0.627646
13시-14시 승차인원      0.649123      0.754069      0.584699      0.653550
13시-14시 하차인원      0.436633      0.700650      0.342490      0.622707
14시-15시 승차인원      0.529939      0.816925      0.453732      0.734724
14시-15시 하차인원      0.522963      0.675586      0.431149      0.576012
15시-16시 승차인원      0.435369      0.842001      0.353412      0.785042
15시-16시 하차인원      0.639966      0.610809      0.556837      0.481274
16시-17시 승차인원      0.375139      0.849045      0.289792      0.808859
16시-17시 하차인원      0.697258      0.574882      0.620801      0.428240
17시-18시 승차인원      0.195467      0.899614      0.115276      0.935540
17시-18시 하차인원      0.737540      0.540342      0.669286      0.377138
18시-19시 승차인원      0.125109      0.889260      0.051503      0.955741
18시-19시 하차인원      0.828117      0.460816      0.778191      0.280473
19시-20시 승차인원      0.244180      0.878013      0.155474      0.884896
19시-20시 하차인원      0.897209      0.355431      0.857458      0.189345
20시-21시 승차인원      0.281982      0.797222      0.190160      0.784046
20시-21시 하차인원      0.916686      0.317230      0.879470      0.153347
21시-22시 승차인원      0.280568      0.743704      0.183173      0.701026
21시-22시 하차인원      0.944245      0.285379      0.913870      0.123778
22시-23시 승차인원      0.279236      0.655704      0.181370      0.604404
22시-23시 하차인원      0.950822      0.266691      0.927844      0.099597
23시-24시 승차인원      0.301953      0.536800      0.210696      0.478778
23시-24시 하차인원      0.950393      0.237141      0.927696      0.081975
00시-01시 승차인원      0.300698      0.545423      0.217905      0.479655
00시-01시 하차인원      0.894422      0.235669      0.867831      0.097410
01시-02시 승차인원      0.553420      0.385417      0.515504      0.273462
01시-02시 하차인원      0.671707      0.228535      0.657367      0.151939
02시-03시 승차인원           NaN           NaN           NaN           NaN
02시-03시 하차인원     -0.069950      0.185388     -0.074623      0.115203
03시-04시 승차인원           NaN           NaN           NaN           NaN
03시-04시 하차인원           NaN           NaN           NaN           NaN
작업일자                   NaN           NaN           NaN           NaN

              08시-09시 승차인원  ...  23시-24시 하차인원  00시-01시 승차인원  00시-01시 하차인원  \
사용월                    NaN  ...           NaN           NaN           NaN
04시-05시 승차인원      0.422188  ...      0.505057      0.174833      0.659035
04시-05시 하차인원      0.525369  ...      0.634721      0.373330      0.658535
05시-06시 승차인원      0.850110  ...      0.888940      0.338598      0.880021
05시-06시 하차인원      0.307357  ...      0.393195      0.596972      0.379410
06시-07시 승차인원      0.974622  ...      0.950393      0.300698      0.894422
06시-07시 하차인원      0.162429  ...      0.237141      0.545423      0.235669
07시-08시 승차인원      0.984037  ...      0.927696      0.217905      0.867831
07시-08시 하차인원     -0.016729  ...      0.081975      0.479655      0.097410
08시-09시 승차인원      1.000000  ...      0.925431      0.244701      0.842470
08시-09시 하차인원     -0.083516  ...      0.022507      0.414582      0.060375
09시-10시 승차인원      0.986421  ...      0.936601      0.326524      0.851518
09시-10시 하차인원      0.000971  ...      0.129908      0.588159      0.155534
10시-11시 승차인원      0.915218  ...      0.923174      0.489579      0.855838
10시-11시 하차인원      0.164241  ...      0.333118      0.709699      0.359698
11시-12시 승차인원      0.782947  ...      0.850717      0.636299      0.807186
11시-12시 하차인원      0.312225  ...      0.513331      0.792092      0.534470
12시-13시 승차인원      0.713811  ...      0.814684      0.709169      0.784871
12시-13시 하차인원      0.338851  ...      0.558229      0.823793      0.587474
13시-14시 승차인원      0.602475  ...      0.731348      0.755729      0.719699
13시-14시 하차인원      0.349851  ...      0.563107      0.828235      0.593162
14시-15시 승차인원      0.471301  ...      0.628413      0.779881      0.630454
14시-15시 하차인원      0.441896  ...      0.643315      0.833841      0.663241
15시-16시 승차인원      0.370027  ...      0.539706      0.777590      0.554641
15시-16시 하차인원      0.567779  ...      0.744953      0.800780      0.748260
16시-17시 승차인원      0.307721  ...      0.480386      0.770749      0.499894
16시-17시 하차인원      0.630039  ...      0.798062      0.787190      0.790821
17시-18시 승차인원      0.131342  ...      0.286866      0.662362      0.314525
17시-18시 하차인원      0.679942  ...      0.837045      0.780122      0.815258
18시-19시 승차인원      0.062029  ...      0.204493      0.590432      0.241612
18시-19시 하차인원      0.788365  ...      0.913957      0.729111      0.881457
19시-20시 승차인원      0.172961  ...      0.348953      0.748407      0.375406
19시-20시 하차인원      0.865755  ...      0.968800      0.657090      0.932442
20시-21시 승차인원      0.208226  ...      0.414771      0.797023      0.437924
20시-21시 하차인원      0.893314  ...      0.979445      0.602322      0.927805
21시-22시 승차인원      0.198751  ...      0.432164      0.878716      0.462017
21시-22시 하차인원      0.926716  ...      0.986960      0.531905      0.922461
22시-23시 승차인원      0.199562  ...      0.457073      0.947729      0.491011
22시-23시 하차인원      0.940267  ...      0.988936      0.496003      0.923454
23시-24시 승차인원      0.228467  ...      0.506910      0.984619      0.550101
23시-24시 하차인원      0.925431  ...      1.000000      0.504951      0.959559
00시-01시 승차인원      0.244701  ...      0.504951      1.000000      0.528941
00시-01시 하차인원      0.842470  ...      0.959559      0.528941      1.000000
01시-02시 승차인원      0.495036  ...      0.654051      0.549554      0.673428
01시-02시 하차인원      0.597943  ...      0.737250      0.405272      0.869205
02시-03시 승차인원           NaN  ...           NaN           NaN           NaN
02시-03시 하차인원     -0.079044  ...     -0.063570      0.034647      0.002523
03시-04시 승차인원           NaN  ...           NaN           NaN           NaN
03시-04시 하차인원           NaN  ...           NaN           NaN           NaN
작업일자                   NaN  ...           NaN           NaN           NaN

              01시-02시 승차인원  01시-02시 하차인원  02시-03시 승차인원  02시-03시 하차인원  \
사용월                    NaN           NaN           NaN           NaN
04시-05시 승차인원      0.284914      0.862748           NaN     -0.037677
04시-05시 하차인원      0.388894      0.603013           NaN     -0.068644
05시-06시 승차인원      0.521718      0.720809           NaN     -0.052796
05시-06시 하차인원      0.467303      0.303401           NaN      0.076453
06시-07시 승차인원      0.553420      0.671707           NaN     -0.069950
06시-07시 하차인원      0.385417      0.228535           NaN      0.185388
07시-08시 승차인원      0.515504      0.657367           NaN     -0.074623
07시-08시 하차인원      0.273462      0.151939           NaN      0.115203
08시-09시 승차인원      0.495036      0.597943           NaN     -0.079044
08시-09시 하차인원      0.230017      0.156381           NaN      0.230604
09시-10시 승차인원      0.524735      0.619759           NaN     -0.074292
09시-10시 하차인원      0.247486      0.183211           NaN      0.154903
10시-11시 승차인원      0.573096      0.639227           NaN     -0.056963
10시-11시 하차인원      0.358356      0.346046           NaN      0.129798
11시-12시 승차인원      0.593601      0.624114           NaN     -0.039829
11시-12시 하차인원      0.478828      0.479184           NaN      0.126420
12시-13시 승차인원      0.595609      0.619608           NaN     -0.008408
12시-13시 하차인원      0.494237      0.515823           NaN      0.132015
13시-14시 승차인원      0.566070      0.598252           NaN      0.025465
13시-14시 하차인원      0.487446      0.514817           NaN      0.127845
14시-15시 승차인원      0.548187      0.537175           NaN      0.057669
14시-15시 하차인원      0.529627      0.562327           NaN      0.133616
15시-16시 승차인원      0.500871      0.488771           NaN      0.074257
15시-16시 하차인원      0.567595      0.613659           NaN      0.121360
16시-17시 승차인원      0.460458      0.447998           NaN      0.089832
16시-17시 하차인원      0.606470      0.636681           NaN      0.088491
17시-18시 승차인원      0.358688      0.322338           NaN      0.127038
17시-18시 하차인원      0.619228      0.640904           NaN      0.037736
18시-19시 승차인원      0.340474      0.286472           NaN      0.232392
18시-19시 하차인원      0.652064      0.682578           NaN     -0.002910
19시-20시 승차인원      0.413529      0.357785           NaN      0.173024
19시-20시 하차인원      0.653714      0.717804           NaN     -0.031588
20시-21시 승차인원      0.444743      0.408686           NaN      0.133328
20시-21시 하차인원      0.635248      0.696331           NaN     -0.063976
21시-22시 승차인원      0.469997      0.407680           NaN      0.094728
21시-22시 하차인원      0.613650      0.686572           NaN     -0.078379
22시-23시 승차인원      0.489513      0.408224           NaN      0.060403
22시-23시 하차인원      0.600599      0.693704           NaN     -0.085715
23시-24시 승차인원      0.542877      0.447891           NaN      0.041290
23시-24시 하차인원      0.654051      0.737250           NaN     -0.063570
00시-01시 승차인원      0.549554      0.405272           NaN      0.034647
00시-01시 하차인원      0.673428      0.869205           NaN      0.002523
01시-02시 승차인원      1.000000      0.512441           NaN      0.099451
01시-02시 하차인원      0.512441      1.000000           NaN      0.123159
02시-03시 승차인원           NaN           NaN           NaN           NaN
02시-03시 하차인원      0.099451      0.123159           NaN      1.000000
03시-04시 승차인원           NaN           NaN           NaN           NaN
03시-04시 하차인원           NaN           NaN           NaN           NaN
작업일자                   NaN           NaN           NaN           NaN

              03시-04시 승차인원  03시-04시 하차인원  작업일자
사용월                    NaN           NaN   NaN
04시-05시 승차인원           NaN           NaN   NaN
04시-05시 하차인원           NaN           NaN   NaN
05시-06시 승차인원           NaN           NaN   NaN
05시-06시 하차인원           NaN           NaN   NaN
06시-07시 승차인원           NaN           NaN   NaN
06시-07시 하차인원           NaN           NaN   NaN
07시-08시 승차인원           NaN           NaN   NaN
07시-08시 하차인원           NaN           NaN   NaN
08시-09시 승차인원           NaN           NaN   NaN
08시-09시 하차인원           NaN           NaN   NaN
09시-10시 승차인원           NaN           NaN   NaN
09시-10시 하차인원           NaN           NaN   NaN
10시-11시 승차인원           NaN           NaN   NaN
10시-11시 하차인원           NaN           NaN   NaN
11시-12시 승차인원           NaN           NaN   NaN
11시-12시 하차인원           NaN           NaN   NaN
12시-13시 승차인원           NaN           NaN   NaN
12시-13시 하차인원           NaN           NaN   NaN
13시-14시 승차인원           NaN           NaN   NaN
13시-14시 하차인원           NaN           NaN   NaN
14시-15시 승차인원           NaN           NaN   NaN
14시-15시 하차인원           NaN           NaN   NaN
15시-16시 승차인원           NaN           NaN   NaN
15시-16시 하차인원           NaN           NaN   NaN
16시-17시 승차인원           NaN           NaN   NaN
16시-17시 하차인원           NaN           NaN   NaN
17시-18시 승차인원           NaN           NaN   NaN
17시-18시 하차인원           NaN           NaN   NaN
18시-19시 승차인원           NaN           NaN   NaN
18시-19시 하차인원           NaN           NaN   NaN
19시-20시 승차인원           NaN           NaN   NaN
19시-20시 하차인원           NaN           NaN   NaN
20시-21시 승차인원           NaN           NaN   NaN
20시-21시 하차인원           NaN           NaN   NaN
21시-22시 승차인원           NaN           NaN   NaN
21시-22시 하차인원           NaN           NaN   NaN
22시-23시 승차인원           NaN           NaN   NaN
22시-23시 하차인원           NaN           NaN   NaN
23시-24시 승차인원           NaN           NaN   NaN
23시-24시 하차인원           NaN           NaN   NaN
00시-01시 승차인원           NaN           NaN   NaN
00시-01시 하차인원           NaN           NaN   NaN
01시-02시 승차인원           NaN           NaN   NaN
01시-02시 하차인원           NaN           NaN   NaN
02시-03시 승차인원           NaN           NaN   NaN
02시-03시 하차인원           NaN           NaN   NaN
03시-04시 승차인원           NaN           NaN   NaN
03시-04시 하차인원           NaN           NaN   NaN
작업일자                   NaN           NaN   NaN

[50 rows x 50 columns]